# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

# Parametre de services
parameters:
    RegistrationType: UserBundle\Form\RegistrationType
    upload_image: UserBundle\Services\UploadImage
    upload_directory: '%kernel.root_dir%/../web/Uploads/profiles/'

# Declaration de services
services:
    user.form.registartion:
        class: "%RegistrationType%"
        tags:
            -  { name: form.type, alias: app_user_registration }
    # Service d'upload d'images
    app.images_uploader:
        class: "%upload_image%" 
        arguments: ["%upload_directory%","@security.token_storage"]