<?php

namespace UserBundle\Repository;

/**
 * DataUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataUserRepository extends \Doctrine\ORM\EntityRepository
{
	// public function getProfile()
	// {

	// 	$qb = $this->createQueryBuilder('profile');

 //        $qb->update('profile.path')
 //           ->where('profile.user = ?user_id')
 //           ->setParameter('user_id', $userId);
 //        ;
    
 //        return $qb->execute();    
	// }
}
