<?php

namespace UserBundle\Repository;

/**
 * ProfileUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileUserRepository extends \Doctrine\ORM\EntityRepository
{
}
